"""empty message

Revision ID: 7d9c3a803f8b
Revises: 3dcbed3b8e74
Create Date: 2022-10-01 14:17:06.729857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9c3a803f8b'
down_revision = '3dcbed3b8e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_tag',
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column('places', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'phone')
    op.drop_table('deal_tag')
    # ### end Alembic commands ###
