"""empty message

Revision ID: 9846a17db41d
Revises: 5e0fcdfc33db
Create Date: 2022-09-25 14:38:20.883003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9846a17db41d'
down_revision = '5e0fcdfc33db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('events', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('events', 'contents')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('events', sa.Column('contents', mysql.TEXT(), nullable=False))
    op.drop_column('events', 'description')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
