"""empty message

Revision ID: fadac82d05f8
Revises: 10b968c90115
Create Date: 2022-09-30 14:06:39.352787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadac82d05f8'
down_revision = '10b968c90115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('url', sa.Text(), nullable=False))
    op.add_column('deals', sa.Column('img', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'img')
    op.drop_column('deals', 'url')
    # ### end Alembic commands ###
